### ISSUE TITLE
局所状態密度計算

### ISSUE THREAD

**Issue by matelier** [Materials-Science-Software-Consortium/phase0_tutorial_wsl#18]
[4.2. 局所状態密度計算](https://phase0-tutorial-wsl.readthedocs.io/ja/latest/surf.html#id9)

では`局所状態密度`だけでなく`仕事関数`も計算して解析しています。
見出しに`仕事関数`も表記した方が良いと思いました。

**Comment by jkoga-asms** [comment]
そうですね．修正しました
cf3ebbfefba4390bf7552b87106bbc4a3af609f4
