### ISSUE TITLE
付録Linuxコマンド

### ISSUE THREAD

**Issue by matelier** [Materials-Science-Software-Consortium/phase0_tutorial_wsl#5]
https://phase0-tutorial-wsl.readthedocs.io/ja/latest/sup.html#linux

実行例において、コマンドとその実行結果が同一行に表示されて、わかりにくいです。

（例）
```
% ls nfinp.data file_names.data
```

また、コマンドの説明が改行されずに、表の横幅がとても長く、見にくく思います。（特に`cp`コマンド）

**Comment by jkoga-asms** [comment]
対応しようとしましたが，`cp`と`mv`のところはローカルでみるのとreadthedocs上でみるのと表示が変わるみたいですね
もう少しやってみます

**Comment by jkoga-asms** [comment]
"座標データ変換"の表も見づらいですね

**Comment by matelier** [comment]
ここからCSSをパクってくると、レイアウトが変わるのではないかと思います。
（よくなるのかどうかは、わかりません）

https://github.com/Materials-Science-Software-Consortium/phase0_manual_rtd/tree/main/_static/css
